### ISSUE TITLE
brands

### ISSUE THREAD

**Issue by techmandan** [devgg/fonticon#23]
All brands supported by font awesome are missing from the list, such as steam, facebook, twitter etc.
Please add them, thanks

**Comment by devgg** [comment]
This is related to #8. From the license I gather that I should not use the brand icons on fonticon. Do you have a good usecase for the brand icons?

"Please do not use brand logos for any purpose except to represent the company, product, or service to which they refer."

**Comment by devgg** [comment]
If you purchased Font Awesome Pro you can now do this [link to instructions](https://github.com/devgg/fonticon#font-awesome-pro).
