### ISSUE TITLE
allow upload

### ISSUE THREAD

**Issue by cup** [devgg/fonticon#27]
I recently notice that this site includes none of the PRO icons, for example:

https://fontawesome.com/icons?q=tv

it might be helpful for people who have purchased them if they could upload them
to FontIcon in order to turn them into Favicons

**Comment by devgg** [comment]
Thanks for bringing this up!
I added support for this (e3d124398f643e144699c4b9bb01bc99183c9dad). Would be nice if you test this out :) ([link](https://fontawesome.com/start))!

**Comment by cup** [comment]
@devgg appreciated - but I havent yet made a purchase

so i cant help to test in this case

i find the implementation restrictive because it would only allow for Font Awesome PRO - not any arbitrary SVG which would have been possible with my original suggestion

thank you
