### ISSUE TITLE
Update to latest Font Awesome version

### ISSUE THREAD

**Issue by nicklangridge** [devgg/fonticon#37]
There are new icons in the latest version (now 5.12.0)

Thanks!

**Comment by fysidm** [comment]
I've updated to FontAwesome 5.13.0, but I cannot push my PR to this repository.

I got this error when publish my PR.
```
remote: Permission to devgg/fonticon.git denied to fysidm.
fatal: unable to access 'https://github.com/devgg/fonticon.git/': The requested URL returned error: 403
```

**Comment by fysidm** [comment]
Never mind. 
It was my first PR. lol

#39
