### ISSUE TITLE
Pro integration not showing icons

### ISSUE THREAD

**Issue by CDarbonne** [devgg/fonticon#41]
I have followed the instructions to integrate Pro license icons. After replacing the tag with the generated one and running window.enableFAPro() in the console, the icons themselves all disappear and only the names of each original free icon remain. No pro icons are added, name only or otherwise. 

Thanks

**Comment by exetico** [comment]
I've followed the guide, and it's working - sort of. It's loading the icons and so on, but the Pro-icons are not showing up. 

I tried to search for [this](https://fontawesome.com/icons/house-signal?style=duotone) with no luck.

And my icons was loaded, like they should, with my Pro-key:
![image](https://user-images.githubusercontent.com/3549445/79970471-41f73380-8493-11ea-9a3d-bb346300da31.png)

**Comment by exetico** [comment]
So, i cloned the repo, and builded it locally with Font Awesome Pro. I changed `initIcons(s, false);` to `initIcons(s, true);` in `index.js`.

But, it's the same story. No pro-icons is listed:
![image](https://user-images.githubusercontent.com/3549445/79971652-e6c64080-8494-11ea-84c2-013a790e2e8c.png)

**Comment by fysidm** [comment]
Hmm...

The previous version 5.8.1 [Font-Awesome-Pro](https://github.com/FortAwesome/Font-Awesome-Pro) is not found now.

Maybe they moved Pro icons to their private repository.

I only updated the free icons of FontAwesome to 5.13.0, and it causes Pro icons disappear.
My bad.

@devgg should we rollback to 5.8.1 which ensured the Pro feature is working as usual?

**Comment by devgg** [comment]
Pro support has been removed as it is not quite clear if it is allowed by the license.
