### ISSUE TITLE
Allow selecting version of fontawesome (4 vs 5 vs 6)

### ISSUE THREAD

**Issue by nzgrover** [devgg/fonticon#54]
Icons have changed between versions. Our project is using version 4 of fontawesome, and we'd like to create a favicon that matches.

**Comment by devgg** [comment]
I will not be supporting multiple fontawesome versions. If you would like to use older versions feel free to use [import_icon_data.py](https://github.com/devgg/fonticon/blob/master/util/import_icon_data.py) with an older version and run the site locally,
