### ISSUE TITLE
CORS Error Missing Allow Origin while trying to dowload the .ico

### ISSUE THREAD

**Issue by alexisdal** [devgg/fonticon#56]
observed on Windows 10 using Chrome 93.0.4577.82 and Firefox 93.0b5 (64 bits)

Steps to reproduce
1. navigate to https://gauger.io/fonticon/
2. hit the download button

Observe that no file is downloaded at all.

Looking in the debugger (F12) I see 
CORS Error Missing Allow Origin error
It looks like the browser refuses to make the request to 
POST | https://fonticon-207412.appspot.com/

I see also 
500 Server ErrorThe server encountered an error and could not complete your request.
Please try again in 30 seconds.

I can't use the service. too bad, it was exactly what I needed

**Comment by devgg** [comment]
Thanks for reporting this. Please choose `.ico (advanced)` next to download which still works.
I will have a look today!

**Comment by devgg** [comment]
Looks like it is fixed.
Let me know if it doesn't work for you.
