### ISSUE TITLE
Remove/hide brand icons

### ISSUE THREAD

**Issue by wustep** [devgg/FontIcon#8]
Font-awesome advises not to use brand icons except to ["represent the represent the company, product, or service to which they refer."](https://fontawesome.com/license?from=io) So it might be safer to remove or hide [all of them](https://fontawesome.com/icons?d=gallery&s=brands) so nobody gets in trouble! 

I personally was looking at using the superpowers one, but that's apparently a brand logo :(. 

thanks,
Stephen

**Comment by devgg** [comment]
Thanks for pointing this out. Is fixed now :)
